CasparCG/client

src/Widgets/Inspector/InspectorTemplateWidget.cpp

If we try to add stored data when rundown is empty then we get sigsegv. I have got sigsegvs randomly also when there were selected elements other then template. So I think we should add stored data only if template is selected which can be checked by examining this->model property.

Verify that "stored data" are added to template

---

src/Caspar/CasparDevice.cpp
src/Common/Global.h
src/Common/Timecode.cpp
src/Common/Timecode.h
src/Core/Models/OscFileModel.cpp
src/Core/Models/OscFileModel.h
src/Widgets/OscTimeWidget.cpp
src/Widgets/OscTimeWidget.h
src/Widgets/OscTimeWidget.ui
src/Widgets/Rundown/RundownMovieWidget.cpp

For some stupid reason we still use frame rates with drop-frame in the US. Server reports these as 100/2997 or even 1000000/29970029, which screws up Client's fps math.

Properly handle drop-frame frame rates (eg, 29.97, 59.94)

---

src/Widgets/Inspector/InspectorMetadataWidget.cpp
src/Widgets/Rundown/RundownAudioWidget.cpp
src/Widgets/Rundown/RundownMovieWidget.cpp
src/Widgets/Rundown/RundownStillWidget.cpp

To improve readability, strip leading directories from the file name in the movie, audio, still and metadata inspector widgets.
I use the Client on a regular basis for live show production. We have a large file structure with folders within folders for different shows. I find it much easier to find things in the playlist, when only the file names are shown. Otherwise, the names become very long and since the letters are all capital, things gets pretty gnarly.
Of course, this is just my opinion and if you think otherwise, feel free to reject this request. No hurt feelings.

Strip leading directories

---

src/Core/Commands/AnchorCommand.cpp
src/Core/Commands/AnchorCommand.h

AnchorCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/BrightnessCommand.cpp
src/Core/Commands/BrightnessCommand.h

BrightnessCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/ClipCommand.cpp
src/Core/Commands/ClipCommand.h

ClipCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/ContrastCommand.cpp
src/Core/Commands/ContrastCommand.h

ContrastCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/CropCommand.cpp
src/Core/Commands/CropCommand.h

CropCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/DeckLinkInputCommand.cpp
src/Core/Commands/DeckLinkInputCommand.h

DeckLinkInputCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/FadeToBlackCommand.cpp
src/Core/Commands/FadeToBlackCommand.h

FadeToBlackCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/FillCommand.cpp
src/Core/Commands/FillCommand.h

FillCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/LevelsCommand.cpp
src/Core/Commands/LevelsCommand.h

LevelsCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/OpacityCommand.cpp
src/Core/Commands/OpacityCommand.h

OpacityCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/PerspectiveCommand.cpp
src/Core/Commands/PerspectiveCommand.h

PerspectiveCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/RotationCommand.cpp
src/Core/Commands/RotationCommand.h

RotationCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/SaturationCommand.cpp
src/Core/Commands/SaturationCommand.h

SaturationCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/SolidColorCommand.cpp
src/Core/Commands/SolidColorCommand.h

SolidColorCommand: fix typo in transitionDuration (extra "t")

---

src/Core/Commands/VolumeCommand.cpp
src/Core/Commands/VolumeCommand.h

VolumeCommand: fix typo in transitionDuration (extra "t")

---

src/Common/Global.h

Fixed compile issue on Mac OSX due to missing override keyword.

[master] Fixed compile issue on Mac OSX Mojave.

---

src/Widgets/Rundown/RundownTreeWidget.cpp
src/Widgets/Rundown/RundownTreeWidget.h

This pull request enables OSC commands such as `control/preview` to display a media element on the server preview channel defined in the client configuration. It is configured to operate if the client configuration is NOT set to "Show preview on auto-step" mode.
The mode can be switched to always enabling OSC control by removing the final condition, `&& !this->previewOnAutoStep` , in new line number 1946 of RundownTreeWidget.cpp

Enable OSC control of preview

---

README.md

It was already stated that a more minimal installation could suffice but it wasn't stated what is actually required at a minimum. This commit records what additional components on top of the "MSVC 2019 64-bit" component were required to get a successful build.

chore: Document Qt requirements

---

src/Core/Commands/SolidColorCommand.cpp
src/Widgets/Inspector/InspectorSolidColorWidget.cpp

In dd9895c118fa25c8a72a28ed8b5e7254f35d8a76 the `printf` syntax using `%02d` was replaced with `QString` and its `arg` function. The default fill character of `arg` is a whitespace. This broke the formatting of the color code if they had a leading zero in any component.
In 22c838ba5fd26c1b796c8915797fc633a21415d3 this was fixed for `Timecode.cpp`. The same fix was now also applied in the other places.

Fix malformed color command #293

---

src/Core/Commands/TemplateCommand.cpp
src/Core/Commands/TemplateCommand.h
src/Widgets/Library/DeviceFilterWidget.cpp
src/Widgets/Rundown/RundownTreeWidget.cpp
src/Widgets/Rundown/RundownWidget.cpp

File DeviceFilterWidget: Correction based on https://doc.qt.io/qt-6/qcombobox.html#setView
Note: If you want to use the convenience views (like QListWidget, QTableWidget or QTreeWidget), make sure to call setModel() on the combobox with the convenience widgets model before calling this function.
File RundowWidget.cpp: open on dir of the last opened file, to avoid going to the entire path again to open a file on the same directory.
File RundownTreeWidget.cpp: on save as, open folder of the active Rundown or HomeDir if active == DEFAULT_NAME
Files src/Core/Commands/TemplateCommand.cpp, src/Core/Commands/TemplateCommand.h: Uses QT Json library to convert to single line json. Avoids errors on new lines and other caracters that could break the update function call.

Some corrections(Json and correct order of function calls) and some improvements(saveAs,Open).
